### ISSUE TITLE
Template render error

### ISSUE THREAD

**Issue by alexec** [krishnaIndia/gitbook-plugin-customtheme#1]
Error:

```
Template render error: (/Users/alexc/.gitbook/versions/2.0.0/theme/templates/website/page.html) [Line 20, Column 20]
  Template render error: Template render error: Template render error: Template render error: TypeError: undefined is not a function
    at module.exports.book.html.head:end (/Users/alexc/selenium-webdriver-in-practice/docs/node_modules/gitbook-plugin-customtheme/index.js:40:34)
    at /Users/alexc/.gitbook/versions/2.0.0/lib/pluginslist.js:141:21
```

You have:

```
for (var i in config.css) {
```

This does not work on my Mac should use iterate over arrays as follows:

```
for (var i = 0; i < config.css.length: i++) {
```

This bug also exists for the js :(

**Comment by sariha** [comment]
:+1: 

made working with this :
for (var i = 0; i < config.js.length; i++) {

and this :
for (var i = 0; i < config.css.length; i++) {

**Comment by alexec** [comment]
Ty!
